### ISSUE TITLE
PCNT not found

### ISSUE THREAD

**Issue by OmerFarukOruc** [DevX8000/ESP32-PCNT-Arduino-Example#3]
src/main.cpp: In function 'void pcnt_intr_handler(void*)':
src/main.cpp:84:28: error: 'PCNT' was not declared in this scope
     uint32_t intr_status = PCNT.int_st.val;
                            ^~~~
src/main.cpp:84:28: note: suggested alternative: 'OCT'
     uint32_t intr_status = PCNT.int_st.val;
                            ^~~~
                            OCT

**Comment by minix1234** [comment]
Try adding `#include "soc/pcnt_struct.h"`

**Comment by OmerFarukOruc** [comment]
Thanks this solved the problem
